### ISSUE TITLE
Evaluation Failed if disabled 'unique-landmark' rule

### ISSUE THREAD

**Issue by manishsat** [dequelabs/axe-puppeteer#30]
When I disable the 'unique-landmark' rule using below line
```
const axePuppeteer = new AxePuppeteer(page).disableRules('unique-landmark')
const scanResults = await axePuppeteer.analyze();
```

It throws the following exception:

```
An error occurred while scanning website page {{ WEBSITE URL }}.: Evaluation failed: [object Object]
    at Logger.trackExceptionAny (/Users/masatwan/work/accessibility-insights-service/packages/logger/dist/logger.js:83:29)
    at Scanner.<anonymous> (/Users/masatwan/work/accessibility-insights-service/packages/runner/out/src/scanner/scanner.js:43:29)
    at Generator.throw (<anonymous>)
    at rejected (/Users/masatwan/work/accessibility-insights-service/packages/runner/out/src/scanner/scanner.js:17:65)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  jse_shortmsg: '[scanner] An error occurred while scanning website page https://support.microsoft.com/en-us.',
  jse_cause: Error: Evaluation failed: [object Object]
      at ExecutionContext._evaluateInternal (/Users/masatwan/work/accessibility-insights-service/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)
      at async ExecutionContext.evaluate (/Users/masatwan/work/accessibility-insights-service/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    -- ASYNC --
      at ExecutionContext.<anonymous> (/Users/masatwan/work/accessibility-insights-service/node_modules/puppeteer/lib/helper.js:111:15)
      at DOMWorld.evaluate (/Users/masatwan/work/accessibility-insights-service/node_modules/puppeteer/lib/DOMWorld.js:112:20)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)
    -- ASYNC --
      at Frame.<anonymous> (/Users/masatwan/work/accessibility-insights-service/node_modules/puppeteer/lib/helper.js:111:15)
      at AxePuppeteer.<anonymous> (/Users/masatwan/work/accessibility-insights-service/node_modules/axe-puppeteer/dist/axePuppeteer.js:162:53)
      at Generator.next (<anonymous>)
      at fulfilled (/Users/masatwan/work/accessibility-insights-service/node_modules/axe-puppeteer/dist/axePuppeteer.js:4:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5),
  jse_info: {},
```

Is this the expected behavior? 
Any pointers on how to get this resolved is much appreciated.

**Comment by michael-siek** [comment]
We have moved this package here https://github.com/dequelabs/axe-core-npm/. Feel free to reopen this issue if need be.
