### ISSUE TITLE
TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by kamal2222ahmed** [dequelabs/axe-puppeteer#56]
trying to execute axe.puppteer.js
```
const { AxePuppeteer } = require('axe-puppeteer')
const puppeteer = require('puppeteer')

(async () => {
    const browser = await puppeteer.launch()
    const page = await browser.newPage()
    await page.setBypassCSP(true)
    await page.goto('https://dequeuniversity.com/demo/mars/')

    const results = await new AxePuppeteer(page).analyze()
    console.log(results)

    await page.close()
    await browser.close()
})()
```
getting error:
```
ode axe-puppeteer.js
/Users/syedahmed/QA/TIGERTEAM/PROJECT-508-AUTOMATION/PUPPETEER/axe-puppeteer.js:4
(async () => {
^

TypeError: require(...) is not a function
    at Object.<anonymous> (/axe-puppeteer.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)

**Comment by stephenmathieson** [comment]
You need a semicolon in front of `(async () => {`, as suggested by the `README.md` file.

Closing for now. Let me know if you have any other issues.
